name: Build, lint and test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    uses: cloudscape-design/.github/.github/workflows/build-lint-test.yml@main
